apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.repoUrl }}
    backstage.io/kubernetes-id: ${{ values.name }}
  tags:
    - nodejs
    - cloud-run
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.system | default("default") }}
