site_name: ${{ values.name }}
site_description: ${{ values.description }}
repo_url: https://github.com/udhayakiran-stack/${{ values.name }}

nav:
  - Home: index.md
  - API Reference: api.md
  - Architecture: architecture.md
  - Development: development.md

plugins:
  - techdocs-core