name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ '${{ secrets.GCP_SA }}' }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: gke-gcloud-auth-plugin

      - name: Enable GKE Auth Plugin
        run: |
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build \
            -t asia-south1-docker.pkg.dev/backstage-demo-499507/apps/${{ '${{ github.event.repository.name }}' }}:latest \
            .

      - name: Push Docker Image
        run: |
          docker push \
            asia-south1-docker.pkg.dev/backstage-demo-499507/apps/${{ '${{ github.event.repository.name }}' }}:latest

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials backstage-cluster \
            --region asia-south1

      - name: Verify Cluster
        run: |
          kubectl get nodes

      - name: Deploy Application
        run: |
          kubectl apply -f k8s/deployment.yaml

      - name: Deploy Service
        run: |
          kubectl apply -f k8s/service.yaml