name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ '${{ secrets.GCP_SA }}' }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: |
          gcloud auth configure-docker \
          asia-south1-docker.pkg.dev

      - run: |
          docker build \
            -t asia-south1-docker.pkg.dev/backstage-demo-499507/apps/${{ '${{ github.event.repository.name }}' }}:latest .

      - run: |
          docker push \
          asia-south1-docker.pkg.dev/backstage-demo-499507/apps/${{ '${{ github.event.repository.name }}' }}:latest

      - run: |
          gcloud container clusters get-credentials backstage-cluster \
          --region asia-south1

      - run: kubectl apply -f k8s/deployment.yaml
      - run: kubectl apply -f k8s/service.yaml