apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}

  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.repoUrl }}

  tags:
    - react
    - frontend
    - vite

spec:
  type: website
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}