app:
  name: {{ cookiecutter.name }}

image:
  repository: ghcr.io/my-org/{{ cookiecutter.name }}
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: {{ cookiecutter.name }}.example.com